name: Deploy to ECR

on:
 
  push:
    branches: [ master ]
  pull-request:
    branches: [ master ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: my first linux command
      uses: echo piyush
      
